# Generated by Django 5.1.4 on 2024-12-09 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='is_full',
        ),
        migrations.AddField(
            model_name='lecture',
            name='capacity',
            field=models.PositiveIntegerField(default=30, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, verbose_name='Day'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Assignment name')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecture', verbose_name='Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Grade')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.assignment', verbose_name='Assignment')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecture', verbose_name='Lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
