# Generated by Django 5.1.4 on 2024-12-09 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_assignmentsubmission_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.department', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
