# Generated by Django 5.1.4 on 2024-12-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_department_faculty_faculty_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='deadline',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='lecture',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
    ]
