# Generated by Django 5.1.4 on 2024-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename_deadline_assignment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_points',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=4, verbose_name='Max points'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Grade'),
        ),
    ]
