# Generated by Django 5.1.4 on 2024-12-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_lecture_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='time',
            new_name='start_time',
        ),
    ]
