# Generated by Django 5.1.4 on 2024-12-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_assignment_created_at_assignment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Resource name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/', verbose_name='Syllabus'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='resources',
            field=models.ManyToManyField(blank=True, to='course.resource', verbose_name='Resources'),
        ),
    ]
