# Generated by Django 5.1.4 on 2024-12-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_course_credits_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=4100, max_digits=10, verbose_name='Fee'),
            preserve_default=False,
        ),
    ]
