# Generated by Django 5.1.4 on 2024-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_faculty_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='semester',
            field=models.PositiveSmallIntegerField(default=2024, verbose_name='Semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='uni_year',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
