# Generated by Django 5.1.4 on 2024-12-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_lecture_semester_lecture_uni_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='uni_year',
            field=models.PositiveSmallIntegerField(verbose_name='Uni Year'),
        ),
    ]
