# Generated by Django 5.1.4 on 2024-12-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_lecture_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Auditorium name')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
