# Generated by Django 5.1.4 on 2024-12-16 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auditorium'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='start_day',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Day'),
        ),
    ]
