# Generated by Django 5.1.4 on 2024-12-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_lecture_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='has_computers',
            field=models.BooleanField(default=False, verbose_name='Computers'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='capacity',
            field=models.PositiveIntegerField(default=30, verbose_name='Capacity'),
        ),
    ]
