# Generated by Django 5.1.4 on 2024-12-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auditorium_has_computers_alter_auditorium_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
    ]
