# Generated by Django 5.1.4 on 2024-12-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_lecture_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.auditorium', verbose_name='Location'),
        ),
    ]
