# Generated by Django 5.1.4 on 2024-12-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_alter_lecture_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start_date', models.DateField(verbose_name='Date')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
