# Generated by Django 5.1.4 on 2024-12-17 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_remove_registrationaccess_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationaccess',
            name='semester_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Grade')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecture', verbose_name='Lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
