# Generated by Django 5.1.4 on 2024-12-18 12:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_graderecord_failed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_lectures', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Start Day'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
