# Generated by Django 5.1.4 on 2024-12-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_alter_assignment_max_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Fall'), (2, 'Spring')], verbose_name='Semester')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
