# Generated by Django 5.1.4 on 2024-12-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_alter_lecture_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationaccess',
            name='semester_end_date',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.semester', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='registrationaccess',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.semester', verbose_name='Semester'),
        ),
    ]
