# Generated by Django 5.1.4 on 2024-12-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_remove_registrationaccess_semester_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='year',
        ),
    ]
