# Generated by Django 5.1.4 on 2024-12-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_remove_lecture_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationaccess',
            name='year',
        ),
    ]
