# Generated by Django 5.1.4 on 2024-12-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_remove_registrationaccess_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
