# Generated by Django 5.1.4 on 2024-12-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_graderecord_created_at_graderecord_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graderecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='graderecord',
            name='updated_at',
        ),
    ]
