# Generated by Django 5.1.4 on 2024-12-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0040_delete_registrationaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='fee',
        ),
    ]
