# Generated by Django 5.1.4 on 2024-12-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0042_assignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Grade'),
        ),
    ]
