# Generated by Django 5.1.4 on 2024-12-20 14:51

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0043_alter_grade_grade_alter_graderecord_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='start_day_second',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Start Day Second'),
        ),
        migrations.AddField(
            model_name='semester',
            name='final_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Final Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='midterm_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Midterm Start Date'),
            preserve_default=False,
        ),
    ]
