# Generated by Django 5.1.4 on 2024-12-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0044_lecture_start_day_second_semester_final_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(help_text='Example: 2020-2021', max_length=150, verbose_name='Year'),
        ),
    ]
