# Generated by Django 5.1.4 on 2024-12-21 19:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0045_alter_semester_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='აღწერა'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(verbose_name='დედლაინი'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecture', verbose_name='ლექცია'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_points',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='მაქსიმალური ქულათა რაოდენობა'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='დავალების სახელი'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='capacity',
            field=models.PositiveIntegerField(default=30, verbose_name='ტევადობა'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='has_computers',
            field=models.BooleanField(default=False, verbose_name='კომპიუტერებით'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='name',
            field=models.CharField(max_length=50, verbose_name='აუდიტორიის სახელი'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, verbose_name='კურსის კოდი'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='კრედიტები'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.department', verbose_name='დეპარტამენტი'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='კურსის სახელი'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='course.course', verbose_name='პრერეკვიზიტები'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10, verbose_name='დეპარტამენტის კოდი'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, verbose_name='დეპარტამენტის სახელი'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=10, verbose_name='ფაკულტეტის კოდი'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.department', verbose_name='დეპარტამენტი'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ფაკულტეტის სახელი'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.assignment', verbose_name='დავალება'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ქულა'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='სტუდენტი'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='ჩაიჭრა'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ქულა'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='აქტიურია'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecture', verbose_name='ლექცია'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='სტუდენტი'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='სტუდენტების დასაშვები რაოდენობა'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='კურსი'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='დღე'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='დასრულების დრო'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.auditorium', verbose_name='აუდიტორია'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ლექციის სახელი'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_lectures', to=settings.AUTH_USER_MODEL, verbose_name='ლექტორი'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='resources',
            field=models.ManyToManyField(blank=True, to='course.resource', verbose_name='რესურსები'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.semester', verbose_name='სემესტრი'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='ლექციის პირველი დღე'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_day_second',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='ლექციის პირველი დღე შუალედურების შემდეგ'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='დაწყების დრო'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/', verbose_name='სილაბუსი'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='uni_year',
            field=models.PositiveSmallIntegerField(verbose_name='სასწავლო წელი'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='ფაილი'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=50, verbose_name='რესურსის სახელი'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='ბმული'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(verbose_name='დასრულების თარიღი'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='final_start',
            field=models.DateField(verbose_name='დასკვნითი გამოცდების დაწყების თარიღი'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='midterm_start',
            field=models.DateField(verbose_name='შუალედური გამოცდების დაწყების თარიღი'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'შემოდგომა'), (2, 'გაზაფხული')], verbose_name='სემესტრი'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(verbose_name='დაწყების თარიღი'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლდა'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(help_text='Example: 2020-2021', max_length=150, verbose_name='წელი'),
        ),
    ]
