# Generated by Django 5.1.4 on 2024-12-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0048_alter_lecture_day_alter_lecture_day_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_syllabus/', verbose_name='სილაბუსი'),
        ),
    ]
