# Generated by Django 5.1.4 on 2024-12-23 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0049_alter_lecture_syllabus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შეიქმნა')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლდა')),
                ('file', models.FileField(upload_to='assignment_submissions/', verbose_name='ფაილი')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.assignment', verbose_name='დავალება')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='სტუდენტი')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
