# Generated by Django 5.1.4 on 2024-12-18 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_remove_registrationaccess_year'),
        ('payment', '0003_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='course.semester'),
        ),
    ]
