# Generated by Django 5.1.4 on 2024-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lecturer',
            field=models.BooleanField(default=False, verbose_name='Lecturer'),
        ),
    ]
