# Generated by Django 5.1.4 on 2024-12-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_lecture_is_full_lecture_capacity_and_more'),
        ('user', '0003_user_faculty_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lectures',
            field=models.ManyToManyField(blank=True, to='course.lecture', verbose_name='Lectures'),
        ),
    ]
