# Generated by Django 5.1.4 on 2024-12-09 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_assignmentsubmission'),
        ('user', '0004_user_lectures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_present', models.BooleanField(default=False, verbose_name='Present')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecture', verbose_name='Lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'lecture', 'date')},
            },
        ),
    ]
