# Generated by Django 5.1.4 on 2024-12-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_resource_lecture_syllabus_lecture_resources'),
        ('user', '0006_rename_year_of_enrollment_user_enrollment_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lectures',
            field=models.ManyToManyField(blank=True, related_name='users', to='course.lecture', verbose_name='Lectures'),
        ),
    ]
