# Generated by Django 5.1.4 on 2024-12-11 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='GPA'),
        ),
        migrations.AddField(
            model_name='user',
            name='loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Loan'),
        ),
        migrations.AddField(
            model_name='user',
            name='scholarship',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Scholarship'),
        ),
    ]
