# Generated by Django 5.1.4 on 2024-12-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_gpa_user_loan_user_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yearly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yearly fee'),
        ),
    ]
