# Generated by Django 5.1.4 on 2024-12-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_yearly_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='scholarship',
            new_name='government_scholarship',
        ),
        migrations.AddField(
            model_name='user',
            name='university_scholarship',
            field=models.BooleanField(default=False, verbose_name='University scholarship'),
        ),
    ]
