# Generated by Django 5.1.4 on 2024-12-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_faculty_fee'),
        ('user', '0010_rename_scholarship_user_government_scholarship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='users', to='course.course', verbose_name='Courses'),
        ),
    ]
