# Generated by Django 5.1.4 on 2024-12-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gpa',
        ),
    ]
