# Generated by Django 5.1.4 on 2024-12-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='university_scholarship',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yearly_fee',
        ),
    ]
