# Generated by Django 5.1.4 on 2024-12-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
