# Generated by Django 5.1.4 on 2024-12-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_lecturer',
        ),
    ]
