# Generated by Django 5.1.4 on 2024-12-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_user_is_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Professor'), (3, 'Admin'), (4, 'Manager'), (5, 'Alumni')], default=1),
            preserve_default=False,
        ),
    ]
