# Generated by Django 5.1.4 on 2024-12-21 19:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_alter_assignment_created_at_and_more'),
        ('user', '0020_googleoauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='თარიღი'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_hour',
            field=models.BooleanField(default=False, verbose_name='პირველი საათი'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecture', verbose_name='ლექცია'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='second_hour',
            field=models.BooleanField(default=False, verbose_name='მეორე საათი'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='third_hour',
            field=models.BooleanField(default=False, verbose_name='მესამე საათი'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი'),
        ),
        migrations.AlterField(
            model_name='googleoauthtoken',
            name='access_token',
            field=models.TextField(verbose_name='წვდომის ტოკენი'),
        ),
        migrations.AlterField(
            model_name='googleoauthtoken',
            name='refresh_token',
            field=models.TextField(verbose_name='განახლების ტოკენი'),
        ),
        migrations.AlterField(
            model_name='googleoauthtoken',
            name='token_expiry',
            field=models.DateTimeField(verbose_name='ტოკენის ვადა'),
        ),
        migrations.AlterField(
            model_name='googleoauthtoken',
            name='token_type',
            field=models.CharField(default='Bearer', max_length=100, verbose_name='ტოკენის ტიპი'),
        ),
        migrations.AlterField(
            model_name='googleoauthtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth_token', to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='users', to='course.course', verbose_name='კურსები'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='რეგისტრაციის თარიღი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='დაბადების თარიღი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.department', verbose_name='დეპარტამენტი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ელ. ფოსტა'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrollment_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ჩარიცხვის წელი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.faculty', verbose_name='ფაკულტეტი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='government_scholarship',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='სახელმწიფო გრანტი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='პირადი ნომერი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/users/', verbose_name='ფოტოსურათი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='აქტიურია'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='სტაფია'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='სუპერიუზერია'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='გვარი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lectures',
            field=models.ManyToManyField(blank=True, related_name='users', to='course.lecture', verbose_name='ლექციები'),
        ),
        migrations.AlterField(
            model_name='user',
            name='loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ვალი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='ტელეფონის ნომერი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Professor'), (3, 'Admin'), (4, 'Manager'), (5, 'Alumni')], verbose_name='როლი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='მომხმარებლის სახელი'),
        ),
    ]
