# Generated by Django 5.1.4 on 2024-12-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='government_scholarship',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='სახელმწიფო გრანტი'),
        ),
    ]
